service: users

plugins:
  - '@ns3/nx-serverless/plugin'
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true

custom:
  stage: ${opt:stage, 'dev'}
  myEnvironment:
    MESSAGE:
      prod: 'This is production environment'
      dev: 'This is development environment'
  serverless-offline:
    httpPort: ${env:HTTP_PORT}
    lambdaPort: 2334
    noPrependStageInUrl: true
  dotenv:
    # https://github.com/neverendingqs/serverless-dotenv-plugin
    # default: project root
    #path: path/to/my/dotenvfiles
    logging: true
    include:
      - HTTP_PORT

params:
  prod:
    production: true
  default:
    production: false

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.stage}
  endpointType: regional
  timeout: 20
  environment:
    HTTP_PORT: ${env:HTTP_PORT}
    APP_ENV: ${self:custom.stage}
    IS_PRODUCTION: ${param:production}
    NODE_OPTIONS: --enable-source-maps
    MESSAGE: ${self:custom.myEnvironment.MESSAGE.${self:custom.stage}}

functions:
  users:
    handler: src/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true
